name: remote_talent_api
description: The Dart implementation of talentApi that uses remote storage
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies: 
  http: ^0.13.4
  talent_api:
    path: ../talent_api

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
